# Notebook 2: Functions, Imports, NumPy & Pandas

This notebook covers how to write reusable functions, how to import external libraries, and a first look at NumPy arrays and pandas DataFrames.

---

## 1. Functions

A function is a named block of code that you can run whenever you need it. You define a function with `def` and call it by name.

In [4]:
def say_hi(name):
    print("Hello,", name)

say_hi("Alice")
say_hi("Bob")

Hello, Alice
Hello, Bob

### Return values

Most useful functions **return** a result that you can store in a variable.

In [5]:
def fold_change(treated, control):
    return treated / control

fc = fold_change(360, 120)
print("Fold change:", fc)

Fold change: 3.0

### Default parameter values

Parameters can have a default. If the caller does not provide that argument, the default is used.

In [6]:
def is_significant(p_value, threshold=0.05):
    return p_value < threshold

print(is_significant(0.03))              # uses default 0.05
print(is_significant(0.08))              # uses default 0.05
print(is_significant(0.08, threshold=0.1))  # overrides default

True
False
True

### Functions can return multiple values

In [7]:
def describe_list(values):
    return min(values), max(values), sum(values) / len(values)

data = [245.7, 128.3, 456.1, 89.4, 312.8]
minimum, maximum, mean = describe_list(data)

print("Min:", minimum)
print("Max:", maximum)
print("Mean:", round(mean, 1))

Min: 89.4
Max: 456.1
Mean: 246.5

### GC content example

In [8]:
def gc_content(sequence):
    """Calculate GC content of a DNA sequence."""
    sequence = sequence.upper()
    gc_count = sequence.count("G") + sequence.count("C")
    return gc_count / len(sequence)

print("GC content:", round(gc_content("ATCGATCGATCG"), 3))
print("GC content:", round(gc_content("GCGCGCATATAT"), 3))

GC content: 0.5
GC content: 0.5

The text in triple quotes (`"""..."""`), right after `def`, is called a **docstring**. It describes what the function does.

**Try it:** write a function called `mean` that takes a list of numbers and returns their mean. Test it on `[10, 20, 30, 40, 50]`.

In [9]:
# Try it here

---

## 2. Imports

Python comes with many pre-built libraries (also called **modules**). To use them, you must **import** them first.

In [10]:
import math

print("Square root of 16:", math.sqrt(16))
print("Log base 2 of 8:", math.log2(8))
print("Pi:", math.pi)

Square root of 16: 4.0
Log base 2 of 8: 3.0
Pi: 3.141592653589793

### Different ways to import

In [11]:
# Import specific functions
from math import sqrt, log2
print(sqrt(25))
print(log2(16))

5.0
4.0

In [12]:
# Import with an alias (a short nickname)
import math as m
print(m.sqrt(36))

6.0

Aliases are a convention. The standard ones in scientific Python:

```python
import numpy as np
import pandas as pd
import seaborn as sns
```

You will see these everywhere.

In [13]:
import random

print("Random float (0-1):", round(random.random(), 4))
print("Random int (1-10):", random.randint(1, 10))
print("Random choice:", random.choice(["ATG", "TAA", "TAG", "TGA"]))

Random float (0-1): 0.8531
Random int (1-10): 3
Random choice: TAG

---

## 3. NumPy: Numerical Arrays

NumPy is the library for numerical computing. Its core object is the **array** — like a list, but designed for math. The key advantage: operations apply to **every element at once**, without writing a loop.

In [14]:
import numpy as np

expression = np.array([245.7, 128.3, 456.1, 89.4, 312.8])
print("Array:", expression)

Array: [245.7 128.3 456.1  89.4 312.8]

In [15]:
# Element-wise operations — no loop needed
print("Doubled:", expression * 2)
print("Plus 10:", expression + 10)
print("Log2:", np.log2(expression))

Doubled: [491.4 256.6 912.2 178.8 625.6]
Plus 10: [255.7 138.3 466.1  99.4 322.8]
Log2: [7.94075405 7.00337736 8.83320636 6.48220293 8.2890967 ]

In [16]:
# Summary statistics
print("Mean:", round(np.mean(expression), 2))
print("Std dev:", round(np.std(expression), 2))
print("Min:", np.min(expression))
print("Max:", np.max(expression))

Mean: 246.46
Std dev: 131.89
Min: 89.4
Max: 456.1

In [17]:
# Boolean indexing: filter elements by a condition
print("Above 200?", expression > 200)
print("Values above 200:", expression[expression > 200])

Above 200? [ True False  True False  True]
Values above 200: [245.7 456.1 312.8]

Pandas (below) is built on top of NumPy. When you work with a column of numbers in a pandas DataFrame, it is stored as a NumPy array internally.

---

## 4. Pandas: DataFrames

Pandas is the central library for working with tabular data in Python. If you have used spreadsheets, a pandas **DataFrame** is the Python equivalent: data organized in rows and columns.

In [18]:
import pandas as pd

### Creating a DataFrame from a dictionary

In [19]:
data = {
    "gene": ["BRCA1", "TP53", "EGFR", "MYC", "KRAS"],
    "chromosome": [17, 17, 7, 8, 12],
    "expression": [245.7, 128.3, 456.1, 89.4, 312.8]
}

df = pd.DataFrame(data)
df

    gene  chromosome  expression
0  BRCA1          17       245.7
1   TP53          17       128.3
2   EGFR           7       456.1
3    MYC           8        89.4
4   KRAS          12       312.8

### Loading data from a CSV file

In practice you will almost always load data from a file.

In [20]:
url = "https://raw.githubusercontent.com/cgenomicslab/imbb-data-analysis/main/data/cretan_marine_survey.csv"
beaches = pd.read_csv(url)

beaches.head()

,site,region,coast,substrate,night_survey,water_temp,posidonia_cover,umbrellas_per_100m,fireworms_per_m2,avg_fireworm_size_cm,scorpionfish,lionfish,cornetfish,seahorses,sea_urchins_per_m2,seashells_per_m2,fluor_peak_nm
0,Kissamos,Chania,north,sandy,True,25.5,34.0,15,0.3,3.1,0,1,1,2,4.3,10.3,520.0
1,Falasarna,Chania,north,sandy,False,26.6,49.0,8,0.8,6.0,0,1,1,3,4.3,10.2,NaN
2,Kolymvari,Chania,north,pebble,True,26.0,0.0,15,2.8,5.2,3,1,1,0,2.5,0.0,526.0
3,Platanias,Chania,north,sandy,True,25.5,29.0,18,1.0,4.9,1,1,2,1,3.9,11.5,538.0
4,Agioi Apostoloi,Chania,north,sandy,False,25.6,5.0,31,0.3,5.5,1,0,0,0,4.7,10.4,NaN

### Exploring the data

In [21]:
# Number of rows and columns
print("Shape:", beaches.shape)

Shape: (71, 17)

In [22]:
# Column names
print("Columns:", beaches.columns.tolist())

Columns: ['site', 'region', 'coast', 'substrate', 'night_survey', 'water_temp', 'posidonia_cover', 'umbrellas_per_100m', 'fireworms_per_m2', 'avg_fireworm_size_cm', 'scorpionfish', 'lionfish', 'cornetfish', 'seahorses', 'sea_urchins_per_m2', 'seashells_per_m2', 'fluor_peak_nm']

In [23]:
# Data types
beaches.dtypes

site                        str
region                      str
coast                       str
substrate                   str
night_survey               bool
water_temp              float64
posidonia_cover         float64
umbrellas_per_100m        int64
fireworms_per_m2        float64
avg_fireworm_size_cm    float64
scorpionfish              int64
lionfish                  int64
cornetfish                int64
seahorses                 int64
sea_urchins_per_m2      float64
seashells_per_m2        float64
fluor_peak_nm           float64
dtype: object

In [24]:
# Summary statistics for numerical columns
beaches.describe()

,water_temp,posidonia_cover,umbrellas_per_100m,fireworms_per_m2,avg_fireworm_size_cm,scorpionfish,lionfish,cornetfish,seahorses,sea_urchins_per_m2,seashells_per_m2,fluor_peak_nm
count,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,71.000000,30.000000
mean,25.605634,23.098592,12.732394,1.432394,5.574648,1.788732,1.901408,1.760563,1.197183,4.030986,6.430986,554.800000
std,1.196768,21.645953,8.518816,1.059215,2.446497,1.723083,1.148352,0.977822,1.440434,1.086750,4.117822,31.219357
min,23.200000,0.000000,0.000000,0.100000,2.000000,0.000000,0.000000,0.000000,0.000000,1.700000,0.000000,500.000000
25%,24.650000,0.000000,7.000000,0.500000,3.900000,0.000000,1.000000,1.000000,0.000000,3.200000,2.450000,532.750000
50%,25.600000,26.000000,12.000000,1.100000,5.200000,1.000000,2.000000,2.000000,1.000000,4.200000,6.800000,551.500000
75%,26.300000,39.500000,18.500000,2.550000,7.050000,3.000000,3.000000,3.000000,2.000000,4.700000,9.950000,581.750000
max,28.500000,78.000000,38.000000,3.400000,11.400000,6.000000,4.000000,4.000000,6.000000,6.600000,13.100000,616.000000

### Selecting columns

In [25]:
beaches["water_temp"].head()

0    25.5
1    26.6
2    26.0
3    25.5
4    25.6
Name: water_temp, dtype: float64

In [26]:
beaches[["site", "water_temp", "region"]].head()

              site  water_temp  region
0         Kissamos        25.5  Chania
1        Falasarna        26.6  Chania
2        Kolymvari        26.0  Chania
3        Platanias        25.5  Chania
4  Agioi Apostoloi        25.6  Chania

In [27]:
print("Mean temperature:", round(beaches["water_temp"].mean(), 2))
print("Max temperature:", beaches["water_temp"].max())

Mean temperature: 25.61
Max temperature: 28.5

In [28]:
# Unique values and counts
print("Number of regions:", beaches["region"].nunique())
print("Regions:", beaches["region"].unique())

Number of regions: 4
Regions: <StringArray>
['Chania', 'Rethymno', 'Heraklion', 'Lassithi']
Length: 4, dtype: str

In [29]:
beaches["region"].value_counts()

region
Chania       26
Lassithi     18
Heraklion    15
Rethymno     12
Name: count, dtype: int64

**Try it:** print the mean and max of the `umbrellas_per_100m` column.

In [30]:
# Try it here

### Filtering rows

You can filter a DataFrame by applying a condition to a column.

In [31]:
# Beaches with temperature above 24
warm = beaches[beaches["water_temp"] > 24]
print("Warm beaches:", len(warm))
warm.head()

Warm beaches: 68

,site,region,coast,substrate,night_survey,water_temp,posidonia_cover,umbrellas_per_100m,fireworms_per_m2,avg_fireworm_size_cm,scorpionfish,lionfish,cornetfish,seahorses,sea_urchins_per_m2,seashells_per_m2,fluor_peak_nm
0,Kissamos,Chania,north,sandy,True,25.5,34.0,15,0.3,3.1,0,1,1,2,4.3,10.3,520.0
1,Falasarna,Chania,north,sandy,False,26.6,49.0,8,0.8,6.0,0,1,1,3,4.3,10.2,NaN
2,Kolymvari,Chania,north,pebble,True,26.0,0.0,15,2.8,5.2,3,1,1,0,2.5,0.0,526.0
3,Platanias,Chania,north,sandy,True,25.5,29.0,18,1.0,4.9,1,1,2,1,3.9,11.5,538.0
4,Agioi Apostoloi,Chania,north,sandy,False,25.6,5.0,31,0.3,5.5,1,0,0,0,4.7,10.4,NaN

In [32]:
# Beaches in a specific region
chania = beaches[beaches["region"] == "Chania"]
print("Beaches in Chania:", len(chania))

Beaches in Chania: 26

Combine conditions with `&` (and) or `|` (or). Each condition must be in parentheses.

In [33]:
result = beaches[(beaches["water_temp"] > 24) & (beaches["region"] == "Chania")]
print("Warm Chania beaches:", len(result))

Warm Chania beaches: 25

**Try it:** filter for beaches with more than 500 tourists per day. How many are there?

In [34]:
# Try it here

---

## Summary

These three notebooks covered:

- **Notebook 0:** Jupyter, variables, data types, strings, arithmetic
- **Notebook 1:** Lists, dictionaries, conditionals, loops
- **Notebook 2:** Functions, imports, NumPy arrays, pandas DataFrames

If any of these seem complicated, go back and work through the "Try it" cells again before the course starts.