# Notebook 3: A Brief Introduction to R

Some sessions in the second week of the course use R instead of Python. This notebook introduces the basics of R so that you are not seeing the syntax for the first time.

R runs inside Jupyter just like Python — the same interface, the same shortcuts. The only difference is the **kernel** (the engine that executes the code). Make sure your notebook is using an R kernel (check the top right corner).

If you have gone through Notebooks 0–2, many concepts here will feel familiar. The main differences are in syntax, not in logic.

---

## 1. Printing and Variables

In R, you can print a value by simply typing it, or by using `print()`. Variables are created with `=`.

In [19]:
gene_name = "BRCA1"
expression = 245.7
sample_count = 50
is_significant = TRUE

print(gene_name)
print(expression)
print(sample_count)
print(is_significant)

[1] "BRCA1"
[1] 245.7
[1] 50
[1] TRUE

In Jupyter, the last expression in a cell is displayed automatically, just like in Python.

In [20]:
6 * 7

[1] 42

To print a label and a value together, use `paste()`.

In [21]:
print(paste("Gene:", gene_name))
print(paste("Expression:", expression))

[1] "Gene: BRCA1"
[1] "Expression: 245.7"

### Data types

R has similar basic types to Python, with slightly different names:

| Python | R | Example |
|--------|---|--------|
| `str` | `character` | `"BRCA1"` |
| `int` / `float` | `numeric` | `245.7` |
| `bool` | `logical` | `TRUE` / `FALSE` |

Use `class()` to check the type of a value (equivalent to Python's `type()`).

In [22]:
class("BRCA1")
class(245.7)
class(TRUE)

[1] "character"

[1] "numeric"

[1] "logical"

Note: R uses `TRUE` and `FALSE` (all caps), not `True` and `False`.

---

## 2. Arithmetic and Comparisons

Arithmetic works the same as in Python.

In [23]:
a = 10
b = 3

print(paste("Addition:", a + b))
print(paste("Subtraction:", a - b))
print(paste("Multiplication:", a * b))
print(paste("Division:", a / b))
print(paste("Integer division:", a %/% b))
print(paste("Remainder:", a %% b))
print(paste("Power:", a ^ b))

[1] "Addition: 13"
[1] "Subtraction: 7"
[1] "Multiplication: 30"
[1] "Division: 3.33333333333333"
[1] "Integer division: 3"
[1] "Remainder: 1"
[1] "Power: 1000"

Minor differences from Python: power is `^` instead of `**`, integer division is `%/%`, remainder is `%%`.

Comparisons work the same way.

In [24]:
x = 10

x == 10
x != 5
x > 3
x < 3

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

Logical operators: `&` (and), `|` (or), `!` (not) — same symbols as Python uses inside pandas.

---

## 3. Vectors

The most fundamental data structure in R is the **vector** — an ordered collection of values of the same type. You create one with `c()` (short for "combine").

Vectors are roughly equivalent to Python lists or NumPy arrays.

In [25]:
genes = c("BRCA1", "TP53", "EGFR", "MYC", "KRAS")
expression = c(245.7, 128.3, 456.1, 89.4, 312.8)

print(genes)
print(expression)
print(paste("Length:", length(expression)))

[1] "BRCA1" "TP53"  "EGFR"  "MYC"   "KRAS"
[1] 245.7 128.3 456.1  89.4 312.8
[1] "Length: 5"

### Indexing

**Important:** R counts from 1, not from 0.

In [26]:
print(paste("First gene:", genes[1]))
print(paste("Third gene:", genes[3]))

# Slicing: select elements 2 through 4
print(genes[2:4])

[1] "First gene: BRCA1"
[1] "Third gene: EGFR"
[1] "TP53" "EGFR" "MYC"

### Element-wise operations

Like NumPy arrays, R vectors support element-wise operations without writing a loop.

In [27]:
expression = c(245.7, 128.3, 456.1, 89.4, 312.8)

# Multiply every element by 2
expression * 2

[1] 491.4 256.6 912.2 178.8 625.6

In [28]:
# Log2 of every element
log2(expression)

[1] 7.940754 7.003377 8.833206 6.482203 8.289097

### Summary statistics

In [29]:
print(paste("Mean:", mean(expression)))
print(paste("Median:", median(expression)))
print(paste("Std dev:", round(sd(expression), 2)))
print(paste("Min:", min(expression)))
print(paste("Max:", max(expression)))

[1] "Mean: 246.46"
[1] "Median: 245.7"
[1] "Std dev: 147.46"
[1] "Min: 89.4"
[1] "Max: 456.1"

### Boolean indexing

Filter a vector using a condition — same idea as NumPy and pandas.

In [30]:
# Which values are above 200?
expression > 200

[1]  TRUE FALSE  TRUE FALSE  TRUE

In [31]:
# Select only those values
expression[expression > 200]

[1] 245.7 456.1 312.8

**Try it:** create a vector of p-values `c(0.003, 0.15, 0.028, 0.41, 0.001)` and select only the significant ones (less than 0.05).

In [32]:
# Try it here

---

## 4. Data Frames

An R data frame is a table of data — equivalent to a pandas DataFrame. Each column is a vector.

In [33]:
df = data.frame(
    gene = c("BRCA1", "TP53", "EGFR", "MYC", "KRAS"),
    chromosome = c(17, 17, 7, 8, 12),
    expression = c(245.7, 128.3, 456.1, 89.4, 312.8)
)

df

  gene  chromosome expression
1 BRCA1 17         245.7
2 TP53  17         128.3
3 EGFR   7         456.1
4 MYC    8          89.4
5 KRAS  12         312.8

### Exploring a data frame

In [34]:
# First few rows
head(df)

  gene  chromosome expression
1 BRCA1 17         245.7
2 TP53  17         128.3
3 EGFR   7         456.1
4 MYC    8          89.4
5 KRAS  12         312.8

In [35]:
# Dimensions: rows, columns
dim(df)

[1] 5 3

In [36]:
# Column names
colnames(df)

[1] "gene"       "chromosome" "expression"

In [37]:
# Structure (types of each column)
str(df)

'data.frame':	5 obs. of  3 variables:
 $ gene      : chr  "BRCA1" "TP53" "EGFR" "MYC" ...
 $ chromosome: num  17 17 7 8 12
 $ expression: num  245.7 128.3 456.1 89.4 312.8

In [38]:
# Summary statistics
summary(df)

     gene             chromosome     expression
 Length:5           Min.   : 7.0   Min.   : 89.4
 Class :character   1st Qu.: 8.0   1st Qu.:128.3
 Mode  :character   Median :12.0   Median :245.7
                    Mean   :12.2   Mean   :246.5
                    3rd Qu.:17.0   3rd Qu.:312.8
                    Max.   :17.0   Max.   :456.1

### Selecting columns

Use `$` to access a column by name.

In [39]:
df$gene

[1] "BRCA1" "TP53"  "EGFR"  "MYC"   "KRAS"

In [40]:
df$expression

[1] 245.7 128.3 456.1  89.4 312.8

In [41]:
mean(df$expression)

[1] 246.46

### Filtering rows

In [42]:
# Rows where expression is above 200
df[df$expression > 200, ]

  gene  chromosome expression
1 BRCA1 17         245.7
3 EGFR   7         456.1
5 KRAS  12         312.8

In [43]:
# Rows where chromosome is 17
df[df$chromosome == 17, ]

  gene  chromosome expression
1 BRCA1 17         245.7
2 TP53  17         128.3

Note the syntax: `df[rows, columns]`. The comma is required — leaving the column part empty means "all columns".

**Try it:** filter for genes with expression below 150.

In [44]:
# Try it here

### Loading data from a CSV

In [45]:
url = "https://raw.githubusercontent.com/cgenomicslab/imbb-data-analysis/main/data/cretan_beaches.csv"
beaches = read.csv(url)

head(beaches)

  beach_name region    compass_direction longitude beach_type beach_length_m
1 Elafonissi Chania    SW                23.54     sand       1200
2 Balos      Chania    NW                23.59     sand        500
3 Falasarna  Chania    NW                23.46     sand       3000
4 Vai        Lassithi  NE                26.26     sand        200
5 Preveli    Rethymno  S                 24.47     mixed       400
6 Matala     Heraklion S                 24.75     mixed       300
  phoenix_palms juniper_density lionfish_abundance cornetfish_abundance
1  45           7               3                   5
2  25           3               2                   3
3  30           6               2                   4
4 250           2               7                  10
5 800           4               5                   6
6  85           3               6                   7
  sea_temp_celsius wind_speed_kmh annual_rainfall_mm avg_tourists_per_day
1 27.3             22             667                4200
2 26.4             30             599                3800
3 23.6             32             623                2100
4 25.8             35             439                2600
5 24.2             18             528                 650
6 23.6             16             532                 550

In [46]:
dim(beaches)

[1] 27 14

---

## 5. Functions

Functions in R are defined with `function()` and assigned to a name.

In [47]:
fold_change = function(treated, control) {
    return(treated / control)
}

fold_change(360, 120)

[1] 3

In [48]:
gc_content = function(sequence) {
    sequence = toupper(sequence)
    chars = strsplit(sequence, "")[[1]]
    gc = sum(chars == "G") + sum(chars == "C")
    return(gc / nchar(sequence))
}

gc_content("ATCGATCG")

[1] 0.5

---

## 6. Installing and Loading Packages

R packages are the equivalent of Python libraries. You install a package once and load it each time you need it.

In [49]:
# Install a package (only needed once, commented out here)
# install.packages("ggplot2")

# Load a package (needed every session)
# library(ggplot2)

For bioinformatics, many packages are installed from Bioconductor rather than CRAN:

```r
# Install BiocManager (only once)
install.packages("BiocManager")

# Then install Bioconductor packages
BiocManager::install("DESeq2")
```

The course instructors will tell you which packages to install for each session.

---

## Quick Reference: Python vs R

| Concept | Python | R |
|---------|--------|---|
| Assignment | `x = 5` | `x = 5` |
| Print | `print("hello")` | `print("hello")` |
| Type check | `type(x)` | `class(x)` |
| Boolean values | `True` / `False` | `TRUE` / `FALSE` |
| List / Vector | `[1, 2, 3]` | `c(1, 2, 3)` |
| Length | `len(x)` | `length(x)` |
| Indexing | `x[0]` (starts at 0) | `x[1]` (starts at 1) |
| Element-wise ops | `np.log2(x)` | `log2(x)` |
| Create data frame | `pd.DataFrame({...})` | `data.frame(...)` |
| Load CSV | `pd.read_csv("f.csv")` | `read.csv("f.csv")` |
| First rows | `df.head()` | `head(df)` |
| Dimensions | `df.shape` | `dim(df)` |
| Select column | `df["col"]` | `df$col` |
| Filter rows | `df[df["col"] > 5]` | `df[df$col > 5, ]` |
| Define function | `def f(x): return x` | `f = function(x) { return(x) }` |
| Import / Load | `import pandas as pd` | `library(ggplot2)` |
| Install package | `pip install x` | `install.packages("x")` |
| Power | `x ** 2` | `x ^ 2` |